### ISSUE TITLE
how to fix random seed for tf-agent

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#120]
I wonder if tfa_gnn.py with the statement 'tf.random.set_seed(1234)' can keep the same initial policy network for every training nor not.
could you tell me the answer about it? thanks for your reply in advance.

**Comment by patrickhart** [comment]
You can find more information about `tf.random.set_seed` here: https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It does not influence the simulation as this does not rely on TensorFlow. For the simulation, you can set the random seed for numpy as it is used for sampling.

**Comment by tinmodeHuang** [comment]
I had a look at it, but I'm not sure that only using ```tf.random.set_seed``` can fix initial weights of policy network for every training.

**Comment by patrickhart** [comment]
In theory, it should. However, there are various factors, such that you need to e.g. set the random seed for other libraries (e.g., numpy) and it possibly could be dependent on the machine as well.
