### ISSUE TITLE
InteractionNetwork doesn't work properly

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#121]
I just remove the two full connection layers by setting ```"ActorFcLayerParams": [],```and```"CriticJointFcLayerParams": []```in the ```.json``` configuration file, it is the result that InteractionNetwork have got 0 reward all the time in 120,000 episodes, as a consequence, I think the network in ```gnn``` wrapper was never trained and there is probably a toggle to start training.
so I need your help with it, could you give me some constructive advices?

![Screenshot from 2021-06-28 08-44-59](https://user-images.githubusercontent.com/65896325/123564769-39b02c00-d7ed-11eb-8da2-4ce30f13fd38.png)

**Comment by patrickhart** [comment]
How many layers of the GNN are you using then? One/two layers might not be enough with such a limited number of neurons.

I would recommend a mix of GNNs and DNNs in general. To make sure all networks are trainable you can print all trainable parameters and count them. If the number is zero only having the GNN, then your assumption is correct.

**Comment by tinmodeHuang** [comment]
the GNN with 4 layers is constructed in original ```interaction_wrapper.py```, I don't modify it and just remove 2 full-connection layers as top layers. all trainable parameters shown as below:
![Screenshot from 2021-06-28 22-04-08](https://user-images.githubusercontent.com/65896325/123650035-ce05a780-d85c-11eb-94c1-e43beeaeb4b0.png)
the following shows all trainable parameters of GNN with 6 layers of sizes [150, 80, 150, 40, 150, 20], removing 2 full-connection layers connected back is the same as previous GNN.
![Screenshot from 2021-06-28 21-56-08](https://user-images.githubusercontent.com/65896325/123649037-0c4e9700-d85c-11eb-818b-ece96d5a4515.png)
the potential-based reward shaping is used as well, but the GNN without full-connection layers always almost get the lowest reward in 50,000 episodes.
![Screenshot from 2021-06-28 22-17-12](https://user-images.githubusercontent.com/65896325/123652139-9e579f00-d85e-11eb-930f-3ee19f35826c.png)
the ```.json```configuration file
```
 {
    "BehaviorIDMClassic": {
        "MinimumSpacing": 2.0,
        "DesiredTimeHeadway": 1.5,
        "MaxAcceleration": 1.7000000476837158,
        "AccelerationLowerBound": -5.0,
        "AccelerationUpperBound": 8.0,
        "DesiredVelocity": 15.0,
        "ComfortableBrakingAcceleration": 1.6699999570846558,
        "MinVelocity": 0.0,
        "MaxVelocity": 50.0,
        "Exponent": 4,
        "BrakeForLaneEnd": false,
        "BrakeForLaneEndEnabledDistance": 60.0,
        "BrakeForLaneEndDistanceOffset": 15.0,
        "NumTrajectoryTimePoints": 11
    },
    "DynamicModel": {
        "wheel_base": 2.700000047683716,
        "delta_max": 0.20000000298023224,
        "lat_acc_max": 4.0,
        "lon_acceleration_max": 4.0,
        "lon_acceleration_min": -8.0
    },
    "agent": {
        "MaxHistoryLength": 50
    },
    "Visualization": {
        "Agents": {
            "Color": {
                "Other": {
                    "Lines": [
                        0.7,
                        0.7,
                        0.7
                    ],
                    "Face": [
                        0.1,
                        0.7,
                        0.1
                    ]
                },
                "Controlled": {
                    "Lines": [
                        0.0,
                        0.27,
                        0.58
                    ],
                    "Face": [
                        0.49,
                        0.63,
                        0.83
                    ]
                },
                "UseColormapForOtherAgents": false,
                "IfColormapUseLineColorOthers": true
            },
            "Alpha": {
                "Controlled": 1.0,
                "Other": 1
            },
            "ColorRoute": [
                0.2,
                0.2,
                0.2
            ],
            "DrawRoute": false,
            "DrawAgentId": true,
            "DrawEvalGoals": true,
            "EvalGoalColor": [
                0.49,
                0.63,
                0.83
            ],
            "DrawHistory": false,
            "DrawHistoryDrawFace": true
        },
        "Map": {
            "XodrLanes": {
                "Boundaries": {
                    "Color": [
                        0.7,
                        0.7,
                        0.7
                    ],
                    "Alpha": 1.0,
                    "Linewidth": 1.0
                }
            },
            "Plane": {
                "Color": [
                    1,
                    1,
                    1,
                    1
                ],
                "Alpha": 1.0
            }
        },
        "Evaluation": {
            "DrawLTLDebugInfo": false
        }
    },
    "World": {
        "remove_agents_out_of_map": true
    },
    "BehaviorDynamicModel": {
        "IntegrationTimeDelta": 0.05000000074505806
    },
    "ML": {

        "BehaviorContinuousML": {
            "ActionsLowerBound": [
                -5.0,
                -0.2
            ],
            "ActionsUpperBound": [
                4.0,
                0.2
            ]
        },
        "GoalReachedGuiding": {
            "GoalReward": 10.0,
            "CollisionPenalty": -10.0,
            "MaxSteps": 60
        },
        "StateObserver": {
            "VelocityRange": [
                0,
                40
            ],
            "ThetaRange": [
                0,
                6.283185307179586
            ],
            "NormalizationEnabled": true,
            "MaxNumAgents": 5
        },        
        "BehaviorGraphSACAgent": {
            "ActorFcLayerParams": [],
            "CriticObservationFcLayerParams": null,
            "CriticActionFcLayerParams": null,
            "CriticJointFcLayerParams": [],
            "ActorLearningRate": 0.0003,
            "CriticLearningRate": 0.0003,
            "AlphaLearningRate": 0.0003,
            "TargetUpdateTau": 0.05,
            "TargetUpdatePeriod": 3,
            "Gamma": 0.995,
            "RewardScaleFactor": 1.0,
            "AgentName": "gnn_sac_agent",
            "DebugSummaries": false,
            "ReplayBufferCapacity": 50000,
            "ParallelBufferCalls": 1,
            "BatchSize": 512,
            "BufferNumSteps": 2,
            "BufferPrefetch": 3
        },
        "BehaviorTFAAgents": {
            "NumCheckpointsToKeep": 3
        },
        "TFARunner": {
            "EvaluationSteps": 25,
            "InitialCollectionEpisodes": 100,
            "CollectionEpisodesPerStep": 1
        },
        "SACRunner": {
            "NumberOfCollections": 200000,
            "EvaluateEveryNSteps": 100
        }
    }
}
```
I'm trying to train for more episodes.

**Comment by patrickhart** [comment]
As a first suggestion:

```
"ActorFcLayerParams": [],
"CriticJointFcLayerParams": [],
```

try to replace `[]` with `null` so it is congruent with the other notation. This might not work with the parameter sever but could be necessary for the tf.agents modules to work.

You should update to the current version of the master. There is a potential-based reward guidance evaluator.

Further to debug:

* What is the step number in the episodes? Does the agent learn anything? Could try to visualize this.
* Why did you choose the network size like this? Maybe try `[80, 80, 80]`? There is always a layer with 150 neurons in each message passing layer as seen here: https://github.com/bark-simulator/bark-ml/blob/90f41497f8c21193d5d90af37d7907a71355d1cd/bark_ml/library_wrappers/lib_tf_agents/networks/gnns/interaction_wrapper.py#L18
* Did the network with the two output layer work?

**Comment by tinmodeHuang** [comment]
with ```"ActorFcLayerParams": []``` and```"CriticJointFcLayerParams": []```, the GNN with a potential-based reward guidance still performs badly as shown below.

![Screenshot from 2021-06-29 11-55-03](https://user-images.githubusercontent.com/65896325/123735339-9be25d00-d8d1-11eb-98b2-a67a6bc9fcd4.png)

the network with 2 full-connection layers performs well, but its performance appears to depend on those too much.

**Comment by patrickhart** [comment]
> with `"ActorFcLayerParams": []` and`"CriticJointFcLayerParams": []`, the GNN with a potential-based reward guidance still performs badly as shown below.
> 
> ```
>         "RewardShapingEvaluator": {
>             "GoalReward": 10.0,
>             "CollisionPenalty": -10.0,
>             "MaxSteps": 60
>         },
> ```
> 
> ![Screenshot from 2021-06-29 11-55-03](https://user-images.githubusercontent.com/65896325/123735339-9be25d00-d8d1-11eb-98b2-a67a6bc9fcd4.png)
> the maximum step is set up as 60
> ![Screenshot from 2021-06-29 12-09-04](https://user-images.githubusercontent.com/65896325/123735998-d8628880-d8d2-11eb-9c5e-e46bcc6c99bb.png)
> 
> the network with 2 full-connection layers performs well, but its performance appears to depend on those too much.

You are still using the old reward shaping evaluator. The new one can be found here: https://github.com/bark-simulator/bark-ml/blob/master/bark_ml/evaluators/reward_shaping.py

The idea is to use the GNNs as message passing layers in combination with the DNN to learn the actions. The edges of the network are visualized, e.g., in this video: 

![](https://bark-simulator.github.io/static/bark-3fcb6b6298cae46f0e7755260af23e6f.gif)

As can be seen, information is successfully aggregated by the GNN (in a meaningful way). 


![](https://bark-simulator.github.io/static/bark-3fcb6b6298cae46f0e7755260af23e6f.gif)

**Comment by patrickhart** [comment]
Any updates on this issue?

**Comment by tinmodeHuang** [comment]
none! for the time being at least
