### ISSUE TITLE
logging in ```iqn_agent.py```

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#125]
```self.writer.add_scalar('stats/mean_Q', mean_q, 4 * self.steps)```
hello! authors.
I wonder if ```self.steps``` times 4 in order to just scale horizontal axis.

**Comment by patrickhart** [comment]
Could you please provide a link to the source code? I am not familiar with this code and @juloberno might be able to help you out here. Seems like it scales the axis, or that the steps have to be scaled.

**Comment by tinmodeHuang** [comment]
well, https://github.com/bark-simulator/bark-ml/blob/e8e5eae4b6e512f39d7306b3f3374611669a0f33/bark_ml/library_wrappers/lib_fqf_iqn_qrdqn/agent/iqn_agent.py#L90

**Comment by patrickhart** [comment]
I guess, this comment could give a clue about that?

https://github.com/bark-simulator/bark-ml/blob/e8e5eae4b6e512f39d7306b3f3374611669a0f33/bark_ml/library_wrappers/lib_fqf_iqn_qrdqn/agent/base_agent.py#L263
