### ISSUE TITLE
ROI Check

### ISSUE THREAD

**Issue by tobiaskessler** [bark-simulator/bark-ml#150]
https://github.com/bark-simulator/bark-ml/blob/0dff0d8a06dd92866ed2b455f4496e3eab4529ad/bark_ml/environments/external_runtime.py#L84

- return void
- collision check against road corridor
- parameter: add only if in corridor
- drop if too far away based on ego pos (check if ego not NULL!)

**Comment by CesarLiu** [comment]
@tobiaskessler Let's say, we close this issue with the implementation of MVP.
