### ISSUE TITLE
env build failed on ubuntu 16.04

### ISSUE THREAD

**Issue by rongliangzi** [bark-simulator/bark-ml#77]
Hi!
I clone this repo and run install and activate the venv as in readme.md. But when I run `bazel run //examples:discrete_env` (or continuous), the console reported: FAILED: "Build did not complete successfully".
Does bark-ml support ubuntu 16.04?

**Comment by patrickhart** [comment]
Did you install the virtual environment and build BARK-ML within it?
Please provide a more detailed error log.

**Comment by rongliangzi** [comment]
I have installed bark before following the instructions, that is `Bazel > 3(3.4.0)`, `python3.7 python3.7-dev python3-tk`, `virtualenv==16.7.8`, except for `gcc7 (I use gcc 5.4.0 to avoid failure of other software dependencies)`. That works well when running `bazel run //examples:merging(or other)`.

When installing bark-ml, after cloning this repo, I run `bash utils/install.sh` and enter it (`source utils/dev_into.sh`). When I try to run the examples `bazel run //examples:continuous_env`, the following error occurs: 
![error](https://user-images.githubusercontent.com/20415758/90260296-e3105c80-de7d-11ea-9ca7-e3d70c8e536e.jpg)

**Comment by patrickhart** [comment]
You need to use a newer version of gcc as this error seems to be related to std::variant.

**Comment by rongliangzi** [comment]
I have upgraded gcc to 7.2.0, and clone the repo and install it again. But the same error still occurs as above.
![批注 2020-08-16 163443](https://user-images.githubusercontent.com/20415758/90330313-6f399580-dfde-11ea-9517-c6df6e2c6e9e.jpg)

**Comment by patrickhart** [comment]
You could try to change the .bacelrc file to: `build  --cxxopt='-std=c++17' --copt=-O3`, so it actually enforces c++17.
You also need to make sure that bazel actually is using gcc7 (I think you can specify this with the CC flag).

**Comment by patrickhart** [comment]
Closed due to inactivity. If required can reopen this issue.
