### ISSUE TITLE
altough the training iterations comes to 60,000 predefined, the training is still continuous

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#87]
it happened at the time running ```bazel run //examples:tfa -- --mode=train```, I never modify anythings

**Comment by patrickhart** [comment]
Run `bazel run //examples:tfa -- --mode=visualize` first to make sure the runner works. 
Where does this tilmestep come from/is stored in?

**Comment by tinmodeHuang** [comment]
I modified ```NumberOfCollections```in ```sac_runner```.
the command was executed normally

**Comment by patrickhart** [comment]
what does training is still continuous mean? Could you try to elaborate it better for me to understand the problem at hand

**Comment by tinmodeHuang** [comment]
sorry for causing you hard understanding the issue!
the total number of training iterations was specified as 60,000
```c++
class SACRunner(TFARunner):
  def __init__(self,
               environment=None,
               agent=None,
               params=None):
    TFARunner.__init__(self,
                       environment=environment,
                       agent=agent,
                       params=params)
    
    self._number_of_collections =\
      self._params["ML"]["SACRunner"]["NumberOfCollections", "", 60000]
    self._evaluation_interval =\
      self._params["ML"]["SACRunner"]["EvaluateEveryNSteps", "", 100] 
```
but the training process still proceed, what I expected is that the training process terminates at 60,000th steps
```bash
I0415 11:44:43.915612 139738856380224 sac_runner.py:95] Training iterations  75000-76000 took 793.403 seconds (avg. 7.934s / iteration).
```

**Comment by patrickhart** [comment]
Now, I understand the issue!

If you access the `ParameterServer` in BARK with `self._params["ML"]["SACRunner"]["NumberOfCollections", "", 60000]` these are merely the default values.

If, e.g., other values are specified in the JSON, these values will be taken. So search in the json-file you are using for `NumberOfCollections` and change the number there.

Best,
Patrick

**Comment by tinmodeHuang** [comment]
okay, I have a try

**Comment by tinmodeHuang** [comment]
I never found any other place where value of ```NumberOfCollections``` can be specified, maybe I should go back into some old release

**Comment by patrickhart** [comment]
Assuming that you run this file, you can add parameters here as the commented code shows: https://github.com/bark-simulator/bark-ml/blob/b9b42ab8124ab31781573b6a804e762271ca4ce6/examples/tfa_gnn.py#L43

**Comment by tinmodeHuang** [comment]
thanks for reminding so much! I have already noticed the point of problem, ```params = ParameterServer()```without arguments in the last release. if I could have compared that with the latest release, this difference be detected.

**Comment by patrickhart** [comment]
the json is only used if you specify `params = ParameterServer(filename=PATH_TO_JSON.json)`.
otherwise you could specify is as
```
params = ParameterServer()
params["ML"]["SACRunner"]["NumberOfCollections"] = 60000
```
