### ISSUE TITLE
the implementation of GNN-SAC

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#88]
could you tell me where the implementation related to the first legend shown in the picture as below is? it is attractive to me

![evaluation_graph_observer](https://user-images.githubusercontent.com/65896325/114717646-d1ae8580-9d67-11eb-8d3c-b4046817bedb.png)

**Comment by patrickhart** [comment]
At the current time, only the graph-nets library is supported. For legacy code, you can have a look in this repository: https://github.com/mrcoliva/bark-ml

**Comment by tinmodeHuang** [comment]
the error occurred when I attemptted to run ```GCN-SAC```, which have troubled me a long time, could you point me the  
 right way.

**Comment by patrickhart** [comment]
you have to initiale the network in the class itself. you could consider passing it as a lambda function or just creating it within instead of passing it from the outside. 

This code is currently no longer supported. We recommend using the graph-nets library + the current implementation.

**Comment by tinmodeHuang** [comment]
the agent with GNN trained on the ``` merging ```scenario performes far from the one with mlp on the point of mean reward, but they share same parameters. I'll appreciate it if you could give me some suggestions

**Comment by patrickhart** [comment]
1. Which experiment are you running?

2. Are you using a custom implementation?

3. The old implementation referenced on top here had some issues, in specific with non-trainable parameters.

4. What do you mean by `they share the same parameters`?

Some debugging hints: disable @tf.function; create the network within the GNNWrapper and make sure that these are seen as trainable parameters (e.g., print trainable parameters); In general I would recommend you to train an experiment on the master to verify the functionality first and then step-by-step implement your own approach.
