### ISSUE TITLE
how to train model on cpu

### ISSUE THREAD

**Issue by tinmodeHuang** [bark-simulator/bark-ml#92]
my gpu doen't have enough memory, so I want to train model on cpu, but only putting a statement ```os.environ["CUDA_VISIBLE_DEVICES"]='-1'``` in tfa_gnn.py  doesn't work

**Comment by patrickhart** [comment]
If you do not have TensorFlow-gpu installed, then it shouldn't train on the GPU right?

**Comment by tinmodeHuang** [comment]
it is well-known that tensorflow2 supports either cpu or gpu. training is done on gpu with cuda before, but now I expect to train mode on cpu

**Comment by patrickhart** [comment]
maybe try this: https://datascience.stackexchange.com/questions/58845/how-to-disable-gpu-with-tensorflow

**Comment by patrickhart** [comment]
> it is well-known that tensorflow2 supports either cpu or gpu. training is done on gpu with cuda before, but now I expect to train a model on cpu

Is that so? I was not aware of that, why should they bother to then, e.g. offer a cpu version: https://pypi.org/project/tensorflow-cpu/

**Comment by tinmodeHuang** [comment]
with cuda, it seems that tf2 only works on GPU unless disabling cuda
